export const NEGERI = [
    { label: "Johor", value: "Johor" },
    { label: "Kedah", value: "Kedah" },
    { label: "Kelantan", value: "Kelantan" },
    { label: "Melaka", value: "Melaka" },
    { label: "Negeri Sembilan", value: "Negeri Sembilan" },
    { label: "Pahang", value: "Pahang" },
    { label: "Penang", value: "Penang" },
    { label: "Perak", value: "Perak" },
    { label: "Perlis", value: "Perlis" },
    { label: "Selangor", value: "Selangor" },
    { label: "Terengganu", value: "Terengganu" },
    { label: "Sabah", value: "Sabah" },
    { label: "Sarawak", value: "Sarawak" },
    { label: "Kuala Lumpur", value: "Kuala Lumpur" },
    { label: "Labuan", value: "Labuan" },
    { label: "Putrajaya", value: "Putrajaya" }
];


export const DISTRICT = {
    "Johor": [
        { label: "Batu Pahat", value: "Batu Pahat" },
        { label: "Johor Bahru", value: "Johor Bahru" },
        { label: "Kluang", value: "Kluang" },
        { label: "Kota Tinggi", value: "Kota Tinggi" },
        { label: "Kulai", value: "Kulai" },
        { label: "Mersing", value: "Mersing" },
        { label: "Muar", value: "Muar" },
        { label: "Pontian", value: "Pontian" },
        { label: "Segamat", value: "Segamat" },
        { label: "Tangkak", value: "Tangkak" }
    ],
    "Kedah": [
        { label: "Baling", value: "Baling" },
        { label: "Bandar Baharu", value: "Bandar Baharu" },
        { label: "Kota Setar", value: "Kota Setar" },
        { label: "Kuala Muda", value: "Kuala Muda" },
        { label: "Kubang Pasu", value: "Kubang Pasu" },
        { label: "Kulim", value: "Kulim" },
        { label: "Langkawi", value: "Langkawi" },
        { label: "Padang Terap", value: "Padang Terap" },
        { label: "Pendang", value: "Pendang" },
        { label: "Pokok Sena", value: "Pokok Sena" },
        { label: "Sik", value: "Sik" },
        { label: "Yan", value: "Yan" }
    ],
    "Kelantan": [
        { label: "Bachok", value: "Bachok" },
        { label: "Gua Musang", value: "Gua Musang" },
        { label: "Jeli", value: "Jeli" },
        { label: "Kota Bharu", value: "Kota Bharu" },
        { label: "Kuala Krai", value: "Kuala Krai" },
        { label: "Machang", value: "Machang" },
        { label: "Pasir Mas", value: "Pasir Mas" },
        { label: "Pasir Puteh", value: "Pasir Puteh" },
        { label: "Tanah Merah", value: "Tanah Merah" },
        { label: "Tumpat", value: "Tumpat" }
    ],
    "Melaka": [
        { label: "Alor Gajah", value: "Alor Gajah" },
        { label: "Central Melaka", value: "Central Melaka" },
        { label: "Jasin", value: "Jasin" }
    ],
    "Negeri Sembilan": [
        { label: "Jelebu", value: "Jelebu" },
        { label: "Jempol", value: "Jempol" },
        { label: "Kuala Pilah", value: "Kuala Pilah" },
        { label: "Port Dickson", value: "Port Dickson" },
        { label: "Rembau", value: "Rembau" },
        { label: "Seremban", value: "Seremban" },
        { label: "Tampin", value: "Tampin" }
    ],
    "Pahang": [
        { label: "Bentong", value: "Bentong" },
        { label: "Bera", value: "Bera" },
        { label: "Cameron Highlands", value: "Cameron Highlands" },
        { label: "Jerantut", value: "Jerantut" },
        { label: "Kuantan", value: "Kuantan" },
        { label: "Lipis", value: "Lipis" },
        { label: "Maran", value: "Maran" },
        { label: "Pekan", value: "Pekan" },
        { label: "Raub", value: "Raub" },
        { label: "Rompin", value: "Rompin" },
        { label: "Temerloh", value: "Temerloh" }
    ],
    "Penang": [
        { label: "Central Seberang Perai", value: "Central Seberang Perai" },
        { label: "North Seberang Perai", value: "North Seberang Perai" },
        { label: "South Seberang Perai", value: "South Seberang Perai" },
        { label: "Northwest Penang Island", value: "Northwest Penang Island" },
        { label: "Southwest Penang Island", value: "Southwest Penang Island" }
    ],
    "Perak": [
        { label: "Batang Padang", value: "Batang Padang" },
        { label: "Hilir Perak", value: "Hilir Perak" },
        { label: "Kinta", value: "Kinta" },
        { label: "Kerian", value: "Kerian" },
        { label: "Kuala Kangsar", value: "Kuala Kangsar" },
        { label: "Larut, Matang and Selama", value: "Larut, Matang and Selama" },
        { label: "Manjung", value: "Manjung" },
        { label: "Muallim", value: "Muallim" },
        { label: "Perak Tengah", value: "Perak Tengah" },
        { label: "Kampar", value: "Kampar" },
        { label: "Hulu Perak", value: "Hulu Perak" }
    ],
    "Perlis": [
        { label: "Kangar", value: "Kangar" },
        { label: "Padang Besar", value: "Padang Besar" },
        { label: "Arau", value: "Arau" }
    ],
    "Selangor": [
        { label: "Gombak", value: "Gombak" },
        { label: "Hulu Langat", value: "Hulu Langat" },
        { label: "Hulu Selangor", value: "Hulu Selangor" },
        { label: "Klang", value: "Klang" },
        { label: "Kuala Langat", value: "Kuala Langat" },
        { label: "Kuala Selangor", value: "Kuala Selangor" },
        { label: "Petaling", value: "Petaling" },
        { label: "Sabak Bernam", value: "Sabak Bernam" },
        { label: "Sepang", value: "Sepang" }
    ],
    "Terengganu": [
        { label: "Besut", value: "Besut" },
        { label: "Dungun", value: "Dungun" },
        { label: "Hulu Terengganu", value: "Hulu Terengganu" },
        { label: "Kemaman", value: "Kemaman" },
        { label: "Kuala Terengganu", value: "Kuala Terengganu" },
        { label: "Marang", value: "Marang" },
        { label: "Setiu", value: "Setiu" }
    ],
    "Sabah": [
        { label: "Beaufort", value: "Beaufort" },
        { label: "Beluran", value: "Beluran" },
        { label: "Kalabakan", value: "Kalabakan" },
        { label: "Keningau", value: "Keningau" },
        { label: "Kinabatangan", value: "Kinabatangan" },
        { label: "Kota Belud", value: "Kota Belud" },
        { label: "Kota Kinabalu", value: "Kota Kinabalu" },
        { label: "Kota Marudu", value: "Kota Marudu" },
        { label: "Kuala Penyu", value: "Kuala Penyu" },
        { label: "Kudat", value: "Kudat" },
        { label: "Kunak", value: "Kunak" },
        { label: "Lahad Datu", value: "Lahad Datu" },
        { label: "Nabawan", value: "Nabawan" },
        { label: "Papar", value: "Papar" },
        { label: "Penampang", value: "Penampang" },
        { label: "Pitas", value: "Pitas" },
        { label: "Putatan", value: "Putatan" },
        { label: "Ranau", value: "Ranau" },
        { label: "Sandakan", value: "Sandakan" },
        { label: "Semporna", value: "Semporna" },
        { label: "Sipitang", value: "Sipitang" },
        { label: "Tambunan", value: "Tambunan" },
        { label: "Tawau", value: "Tawau" },
        { label: "Telupid", value: "Telupid" },
        { label: "Tenom", value: "Tenom" },
        { label: "Tongod", value: "Tongod" }
    ],
    "Sarawak": [
        { label: "Asajaya", value: "Asajaya" },
        { label: "Bau", value: "Bau" },
        { label: "Belaga", value: "Belaga" },
        { label: "Beluru", value: "Beluru" },
        { label: "Betong", value: "Betong" },
        { label: "Bintulu", value: "Bintulu" },
        { label: "Bukit Mabong", value: "Bukit Mabong" },
        { label: "Dalat", value: "Dalat" },
        { label: "Daro", value: "Daro" },
        { label: "Julau", value: "Julau" },
        { label: "Kabong", value: "Kabong" },
        { label: "Kanowit", value: "Kanowit" },
        { label: "Kapit", value: "Kapit" },
        { label: "Kota Samarahan", value: "Kota Samarahan" },
        { label: "Kuching", value: "Kuching" },
        { label: "Lawas", value: "Lawas" },
        { label: "Limbang", value: "Limbang" },
        { label: "Lubok Antu", value: "Lubok Antu" },
        { label: "Lundu", value: "Lundu" },
        { label: "Marudi", value: "Marudi" },
        { label: "Matu", value: "Matu" },
        { label: "Meradong", value: "Meradong" },
        { label: "Miri", value: "Miri" },
        { label: "Mubong", value: "Mubong" },
        { label: "Mukah", value: "Mukah" },
        { label: "Pakan", value: "Pakan" },
        { label: "Pusa", value: "Pusa" },
        { label: "Samarahan", value: "Samarahan" },
        { label: "Sarikei", value: "Sarikei" },
        { label: "Sebauh", value: "Sebauh" },
        { label: "Selangau", value: "Selangau" },
        { label: "Serian", value: "Serian" },
        { label: "Sibu", value: "Sibu" },
        { label: "Simunjan", value: "Simunjan" },
        { label: "Song", value: "Song" },
        { label: "Sri Aman", value: "Sri Aman" },
        { label: "Subis", value: "Subis" },
        { label: "Tanjung Manis", value: "Tanjung Manis" },
        { label: "Tatau", value: "Tatau" },
        { label: "Tebedu", value: "Tebedu" }
    ],
    "Kuala Lumpur": [
        { label: "Bukit Bintang", value: "Bukit Bintang" },
        { label: "Titiwangsa", value: "Titiwangsa" },
        { label: "Kepong", value: "Kepong" },
        { label: "Batu", value: "Batu" },
        { label: "Wangsa Maju", value: "Wangsa Maju" },
        { label: "Setiawangsa", value: "Setiawangsa" },
        { label: "Lembah Pantai", value: "Lembah Pantai" },
        { label: "Seputeh", value: "Seputeh" },
        { label: "Cheras", value: "Cheras" },
        { label: "Bandar Tun Razak", value: "Bandar Tun Razak" }
    ],
    "Labuan": [
        { label: "Labuan", value: "Labuan" }
    ],
    "Putrajaya": [
        { label: "Putrajaya", value: "Putrajaya" }
    ]
};
       
