export const SENARAI__ASET = [
    {
        "id": 1,
        "status": "Tersedia",
        "asset_category": "Institusi",
        "asset_type": "Alih",
        "asset_class": "Perabot",
        "unit_tag_number": "INV001",
        "unit_name": "Kerusi",
        "unit_model": "KR123456",
        "unit_lokasi": "Bilik Mesyuarat",
    },
    {
        "id": 2,
        "status": "Sedang Diguna",
        "asset_category": "Wakaf",
        "asset_type": " Alih",
        "asset_class": "Perabot",
        "unit_tag_number": "INV002",
        "unit_name": "Meja",
        "unit_model": "MJ654321",
        "unit_lokasi": "Pejabat",
    },
    {
        "id": 3,
        "status": "Penyelenggaraan Berkala",
        "asset_category": "Wakaf",
        "asset_type": " Alih",
        "asset_class": "Elektronik",
        "unit_tag_number": "INV003",
        "unit_name": "Komputer",
        "unit_model": "KP123789",
        "unit_lokasi": "Makmal Komputer",
    },
    {
        "id": 4,
        "status": "Penyelenggaraan",
        "asset_category": "Institusi",
        "asset_type": " Alih",
        "asset_class": "Elektronik",
        "unit_tag_number": "INV004",
        "unit_name": "Pencetak",
        "unit_model": "PR789123",
        "unit_lokasi": "Pejabat",
    },
    {
        "id": 5,
        "status": "Rosak",
        "asset_category": "Wakaf",
        "asset_type": "Tak Alih",
        "asset_class": "Elektronik",
        "unit_tag_number": "INV005",
        "unit_name": "Projektor",
        "unit_model": "PJ456789",
        "unit_lokasi": "Bilik Mesyuarat",
    },
    {
        "id": 6,
        "asset_category": "Institusi",
        "asset_type": "Alih",
        "asset_class": "Elektronik",
        "status": "Pelupusan Berjadual",
        "unit_tag_number": "INV006",
        "unit_name": "Telefon",
        "unit_model": "TL654123",
        "unit_lokasi": "Pejabat",
    }
    // {
    //     "id": 7,
    //     "status": "Rosak",
    //     "unit_tag_number": "7",
    //     "unit_name": "Mesin Fotostat",
    //     "unit_model": "Xerox WorkCentre",
    //     "unit_lokasi": "Pejabat",
    // },
    // {
    //     "id": 8,
    //     "status": "Dalam Prosess",
    //     "unit_tag_number": "8",
    //     "unit_name": "Papan Putih",
    //     "unit_model": " Quartet Corkboard",
    //     "unit_lokasi": "Bilik Mesyuarat",
    // },
    // {
    //     "id": 9,
    //     "status": "Berjaya",
    //     "unit_tag_number": "9",
    //     "unit_name": "Kerusi Roda",
    //     "unit_model": "Herman Miller Embody",
    //     "unit_lokasi": "Pejabat",
    // },
    // {
    //     "id": 10,
    //     "status": "Rosak",
    //     "unit_tag_number": "10",
    //     "unit_name": "Meja Makan",
    //     "unit_model": "IKEA Linnmon",
    //     "unit_lokasi": "Bilik Makan",
    // },
    // {
    //     "id": 11,
    //     "status": "Dalam Prosess",
    //     "unit_tag_number": "11",
    //     "unit_name": "Pembersih Udara",
    //     "unit_model": "Dyson Pure Cool",
    //     "unit_lokasi": "Pejabat",
    // },
    // {
    //     "id": 12,
    //     "status": "Berjaya",
    //     "unit_tag_number": "12",
    //     "unit_name": "Sistem Audio",
    //     "unit_model": "Bose SoundLink",
    //     "unit_lokasi": "Bilik Mesyuarat",
    // },
    // {
    //     "id": 13,
    //     "status": "Rosak",
    //     "unit_tag_number": "13",
    //     "unit_name": "Kamera Keselamatan",
    //     "unit_model": "Hikvision DS-2CE16C0T-IR",
    //     "unit_lokasi": "Pejabat",
    // },
    // {
    //     "id": 14,
    //     "status": "Dalam Prosess",
    //     "unit_tag_number": "14",
    //     "unit_name": "Pintu Keselamatan",
    //     "unit_model": "Abloy EL560",
    //     "unit_lokasi": "Pejabat",
    // },
    // {
    //     "id": 15,
    //     "status": "Berjaya",
    //     "unit_tag_number": "15",
    //     "unit_name": "Sistem Penghawa Dingin",
    //     "unit_model": "Daikin FTV25AXV14",
    //     "unit_lokasi": "Pejabat",
    // }
]