name: Deploy React + Vite to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build for Development
        run: npm run build:dev

      - name: Deploy to Development Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: "dist/*"
          target: "/home/infaqyide/admin/development"
          strip_components: 1
          rm: true

      - name: Development Deployment Summary
        run: |
          echo "✅ **Development deployment successful!**" >> $GITHUB_STEP_SUMMARY
          echo "- Target: /home/infaqyide/admin/development" >> $GITHUB_STEP_SUMMARY

  build-and-deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    needs: build-and-deploy-dev  # runs after dev deployment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build for Staging
        run: npm run build:staging

      - name: Deploy to Staging Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: "dist/*"
          target: "/home/infaqyide/admin/staging"
          strip_components: 1
          rm: true

      - name: Staging Deployment Summary
        run: |
          echo "✅ **Staging deployment successful!**" >> $GITHUB_STEP_SUMMARY
          echo "- Target: /home/infaqyide/admin/staging" >> $GITHUB_STEP_SUMMARY

  build-and-deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    needs: build-and-deploy-staging  # runs after staging deployment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build for Production
        run: npm run build:production

      - name: Deploy to Production Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: "dist/*"
          target: "/home/infaqyide/admin/production"
          strip_components: 1
          rm: true

      - name: Production Deployment Summary
        run: |
          echo "✅ **Production deployment successful!**" >> $GITHUB_STEP_SUMMARY
          echo "- Target: /home/infaqyide/admin/production" >> $GITHUB_STEP_SUMMARY